### ISSUE TITLE
License

### ISSUE THREAD

**Issue by waldyrious** [FLIF-hub/FLIF-hub.github.io#1]
Please add a license to the site's contents. I'd recommend Creative Commons BY-SA.

ps - this was my real motivation for requesting the hosting of the site on github: I wanted the logo hosted somewhere with a clear licensing so I could add it to the [Wikipedia article](https://en.wikipedia.org/wiki/Free_Lossless_Image_Format) :)

**Comment by jonsneyers** [comment]
Done.

**Comment by waldyrious** [comment]
And [done](https://en.wikipedia.org/w/index.php?title=Free_Lossless_Image_Format&oldid=687197332) :)

Please confirm authorship and creation date of the logo, to ensure the [metadata](https://commons.wikimedia.org/wiki/File:FLIF.png#Summary) is accurate (if possible with a publicly available link / archive, but your word works, too).

**Comment by waldyrious** [comment]
Also, are you [this user](https://nl.wikipedia.org/wiki/Gebruiker:Jon_Sneyers)? I could link your name in the file description to the user page if that's ok with you.

**Comment by jonsneyers** [comment]
Actually, I am not the author of that logo. It was made by someone from Norway and shared through this forum post:

https://boards.openpandora.org/topic/18485-free-lossless-image-format-flif/?page=2#comment-398925

**Comment by waldyrious** [comment]
Great, I've updated the data.

@comradekingu when you see this, please confirm you agree with the CC BY-SA license. I don't think "license free as in flurg, as in _flurg laaaif_!" cuts it :)

**Comment by comradekingu** [comment]
Agreed. To avoid confusion, I'll make it a point to specify
https://creativecommons.org/licenses/by-sa/4.0
as it is one-way compatible with GPLv3.
